JCLASS(Light)
JEXPOSE(std::string, uuid, "846455$UUID", jedv_t_hidden, 0)
JEXPOSE(bool, hidden, false, jedv_t_hidden, 0)
JEXPOSE(std::string, name, "846455$NAME", jedv_t_hidden, 0)
JEXPOSE_ENUM(LightType, lightType, LT_Ambient, jedv_t_lighttype, 1)
JEXPOSE_TRANSFORM(XMFLOAT3, position, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.0f, 0.0f), jedv_t_hidden, 1)
JEXPOSE_TRANSFORM(XMFLOAT3, rotation, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.0f, 0.0f), jedv_t_hidden, 1)
JEXPOSE_TRANSFORM(XMFLOAT3, color, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(1.0f, 1.0f, 1.0f), jedv_t_hidden, 1)
JEXPOSE(float, brightness, 1.0f, jedv_t_hidden, 1)
JEXPOSE_TRANSFORM(XMFLOAT3, attenuation, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.01f, 0.02f), jedv_t_hidden, 1)
JEXPOSE(float, coneAngle, 45.0f, jedv_t_hidden, 1)
JEXPOSE(bool, hasShadowMaps, false, jedv_t_hidden, 1)
JEXPOSE(float, dirDist, 30.0f, jedv_t_hidden, 1)
JEXPOSE(unsigned int, shadowMapWidth, 1024, jedv_t_hidden, 1)
JEXPOSE(unsigned int, shadowMapHeight, 1024, jedv_t_hidden, 1)
JEXPOSE(float, viewWidth, 1024, jedv_t_hidden, 1)
JEXPOSE(float, viewHeight, 1024, jedv_t_hidden, 1)
JEXPOSE(float, nearZ, 0.01f, jedv_t_hidden, 1)
JEXPOSE(float, farZ, 350.0f, jedv_t_hidden, 1)
JEXPOSE(float, zBias, 0.0001f, jedv_t_hidden, 1)
JTRACKUUID(Light, Lights, 0)
