JCLASS(Renderable)
JEXPOSE(std::string, uuid, "846455$UUID", jedv_t_hidden, 0)
JEXPOSE(std::string, name, "846455$NAME", jedv_t_string, 0)
JEXPOSE(bool, castShadows, true, jedv_t_boolean, 0)
JEXPOSE(bool, shadowed, true, jedv_t_boolean, 0)
JEXPOSE(bool, hidden, false, jedv_t_boolean, 0)
JEXPOSE(bool, ibl, false, jedv_t_boolean, 1)
JEXPOSE_VECTOR_TRANSFORM(MeshMaterial, meshMaterials, ToMeshMaterial, FromMeshMaterial, {}, jedv_t_vector, 1)
JEXPOSE(std::string, model, "", jedv_t_te_model3d, 1)
JEXPOSE(std::string, animation, "", jdev_t_animation, 1)
JEXPOSE(float, animationTime, 0.0f, jedv_t_hidden, 1)
JEXPOSE(float, animationTimeFactor, 1.0f, jedv_t_hidden, 1)
JEXPOSE(bool, animationPlay, false, jedv_t_hidden, 1)
JEXPOSE(bool, animationLoop, false, jedv_t_hidden, 1)
JEXPOSE_TRANSFORM(XMFLOAT3, position, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.0f, 0.0f), jedv_t_float3, 0)
JEXPOSE_TRANSFORM(XMFLOAT3, rotation, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.0f, 0.0f), jedv_t_float3_angle, 0)
JEXPOSE_TRANSFORM(XMFLOAT3, scale, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(1.0f, 1.0f, 1.0f), jedv_t_float3, 0)
JEXPOSE_SET(int, skipMeshes, {}, jedv_t_hidden, 0)
JEXPOSE_ENUM(D3D_PRIMITIVE_TOPOLOGY, topology, D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST, jedv_t_enum, 1)
JEXPOSE(bool, uniqueMaterialInstance, false, jedv_t_boolean, 1)
JEXPOSE(bool, visible, true, jedv_t_boolean, 0)
JEXPOSE_VECTOR(std::string, cameras, {}, jedv_t_so_camera_vector, 1)
JTRACKUUID(Renderable, Renderables, 0)
JTRACKUUID(Renderable, Animables, 0)
