JCLASS(SoundFX)
JEXPOSE(std::string, uuid, "", jedv_t_string, 0)
JEXPOSE(std::string, name, "", jedv_t_string, 0)
JEXPOSE(std::string, sound, "", jedv_t_te_sound, 1)
JEXPOSE(float, volume, 1.0f, jedv_t_float, 1)
JEXPOSE(bool, autoPlay, false, jedv_t_boolean, 1)
JEXPOSE(bool, loop, false, jedv_t_boolean, 1)
JEXPOSE(bool, hidden, false, jedv_t_boolean, 0)
JEXPOSE_TRANSFORM(XMFLOAT3, position, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.0f, 0.0f), jedv_t_sound_instance_pos, 0)
JEXPOSE_TRANSFORM(XMFLOAT3, rotation, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.0f, 0.0f), jedv_t_sound_instance_rotation, 0)
JEXPOSE(unsigned int, instanceFlags, SoundEffectInstance_Default, jedv_t_sound_instance_flags, 1)
JTRACKUUID(SoundFX, SoundEffects, 0)
JTRACKUUID(SoundFX, Sound3DEffects, 0)
