JCLASS(Model3D)
JEXPOSE(std::string, uuid, "", jedv_t_hidden, 0)
JEXPOSE(std::string, name, "", jedv_t_string, 0)
JEXPOSE(std::string, path, "", jedv_t_model3d_filepath, 1)
JEXPOSE(std::string, shader_vs, "", jedv_t_te_shader, 1)
JEXPOSE(std::string, shader_ps, "", jedv_t_te_shader, 1)
JEXPOSE_VECTOR(std::string, materials, {}, jedv_t_te_material_vector, 1)
