JCLASS(RenderPass)
JEXPOSE(std::string, uuid, "", jedv_t_hidden, 0)
JEXPOSE(std::string, name, "", jedv_t_string, 0)
JEXPOSE_ENUM(RenderPassType, type, RenderPassType_RenderToTexturePass, jedv_t_enum, 1)
JEXPOSE(bool, fitWindow, false, jedv_t_boolean, 1)
JEXPOSE_VECTOR_TRANSFORM(DXGI_FORMAT, renderTargetFormats, ToDXGIFormat, FromDXGIFormat, { DXGI_FORMAT_R8G8B8A8_UNORM }, jedv_t_vector, 1)
JEXPOSE_ENUM(DXGI_FORMAT, depthStencilFormat, DXGI_FORMAT_D32_FLOAT, jedv_t_enum, 1)
JEXPOSE_ENUM(RenderPassMaterialOverride, materialOverride, RenderPassMaterialOverride_None, jedv_t_enum, 1)
JEXPOSE_ENUM(RenderPassRenderCallbackOverride, renderCallbackOverride, RenderPassRenderCallbackOverride_None, jedv_t_enum, 1)