#pragma once
#include <cstdint>
#include <map>

#if defined(_EDITOR)
#include "Shaders/Compiler/ShaderCompilerOutput.h"
#endif

//notifications
struct NotificationTarget {
	bool operator()(const NotificationTarget& a, const NotificationTarget& b) const {
		return (intptr_t)a.target == (intptr_t)b.target;
	}
	bool operator < (const NotificationTarget& b) const {
		return (intptr_t)this->target == (intptr_t)b.target;
	}
	void* target;
};

struct NotificationCallbacks {
	void (*onLoadStart)(void* target) = nullptr;
	void (*onLoadComplete)(void* target, void* source) = nullptr;
	void (*onDestroy)(void* target, void* source) = nullptr;
};
typedef std::map<NotificationTarget, NotificationCallbacks> ChangesNotifications;
template<typename T>
using TemplatesNotification = std::map<T, ChangesNotifications>;

template<typename T>
void NotifyOnLoadStart(ChangesNotifications& notifications) {
	for (auto &[target, callbacks] : notifications) {
		callbacks.onLoadStart(target.target);
	}
}

template<typename T>
void NotifyOnLoadComplete(T* source, ChangesNotifications& notifications) {
	for (auto& [target, callbacks] : notifications) {
		callbacks.onLoadComplete(target.target, (void*)(source));
	}
}

template<typename T>
void NotifyOnDestroy(T* source, ChangesNotifications& notifications) {
	for (auto& [target, callbacks] : notifications) {
		callbacks.onDestroy(target.target, (void*)(source));
	}
}

enum MaterialVariablesTypes {
	MAT_VAR_BOOLEAN,
	MAT_VAR_INTEGER,
	MAT_VAR_UNSIGNED_INTEGER,
	MAT_VAR_RGB,
	MAT_VAR_RGBA,
	MAT_VAR_FLOAT,
	MAT_VAR_FLOAT2,
	MAT_VAR_FLOAT3,
	MAT_VAR_FLOAT4,
	MAT_VAR_MATRIX4X4
};

static std::vector<std::wstring> MaterialVariablesTypesStr = {
	L"BOOLEAN",
	L"INTEGER",
	L"UNSIGNED_INTEGER",
	L"RGB",
	L"RGBA",
	L"FLOAT",
	L"FLOAT2",
	L"FLOAT3",
	L"FLOAT4",
	L"MATRIX4X4"
};

static std::map<MaterialVariablesTypes, std::wstring> MaterialVariablesTypesNames = {
	{MaterialVariablesTypes::MAT_VAR_BOOLEAN, L"BOOLEAN"},
	{MaterialVariablesTypes::MAT_VAR_INTEGER, L"INTEGER"},
	{MaterialVariablesTypes::MAT_VAR_UNSIGNED_INTEGER, L"UNSIGNED_INTEGER"},
	{MaterialVariablesTypes::MAT_VAR_RGB, L"RGB"},
	{MaterialVariablesTypes::MAT_VAR_RGBA, L"RGBA"},
	{MaterialVariablesTypes::MAT_VAR_FLOAT, L"FLOAT"},
	{MaterialVariablesTypes::MAT_VAR_FLOAT2, L"FLOAT2"},
	{MaterialVariablesTypes::MAT_VAR_FLOAT3, L"FLOAT3"},
	{MaterialVariablesTypes::MAT_VAR_FLOAT4, L"FLOAT4"},
	{MaterialVariablesTypes::MAT_VAR_MATRIX4X4, L"MATRIX4X4"},
};

static std::map<std::wstring, MaterialVariablesTypes> StrToMaterialVariablesTypes = {
	{ L"BOOLEAN", MAT_VAR_BOOLEAN },
	{ L"INTEGER", MAT_VAR_INTEGER },
	{ L"UNSIGNED_INTEGER", MAT_VAR_UNSIGNED_INTEGER },
	{ L"RGB", MAT_VAR_RGB },
	{ L"RGBA", MAT_VAR_RGBA },
	{ L"FLOAT", MAT_VAR_FLOAT },
	{ L"FLOAT2", MAT_VAR_FLOAT2 },
	{ L"FLOAT3", MAT_VAR_FLOAT3 },
	{ L"FLOAT4", MAT_VAR_FLOAT4 },
	{ L"MATRIX4X4", MAT_VAR_MATRIX4X4 }
};

static std::map<MaterialVariablesTypes, size_t> MaterialVariablesTypesSizes = {
	{MaterialVariablesTypes::MAT_VAR_BOOLEAN, sizeof(bool)},
	{MaterialVariablesTypes::MAT_VAR_INTEGER, sizeof(int)},
	{MaterialVariablesTypes::MAT_VAR_UNSIGNED_INTEGER, sizeof(unsigned int)},
	{MaterialVariablesTypes::MAT_VAR_RGB, sizeof(float[3])},
	{MaterialVariablesTypes::MAT_VAR_RGBA, sizeof(float[4])},
	{MaterialVariablesTypes::MAT_VAR_FLOAT, sizeof(float)},
	{MaterialVariablesTypes::MAT_VAR_FLOAT2, sizeof(float[2])},
	{MaterialVariablesTypes::MAT_VAR_FLOAT3, sizeof(float[3])},
	{MaterialVariablesTypes::MAT_VAR_FLOAT4, sizeof(float[4])},
	{MaterialVariablesTypes::MAT_VAR_MATRIX4X4, sizeof(float[16])},
};

struct MaterialVariableInitialValue {
	MaterialVariablesTypes variableType;
	std::any value;
};
typedef std::pair<std::wstring, MaterialVariableInitialValue> MaterialInitialValuePair;
typedef std::map<std::wstring, MaterialVariableInitialValue> MaterialInitialValueMap;

struct MaterialVariableMapping {
	MaterialVariablesTypes variableType;
	CBufferVariable mapping;
};
typedef std::map<std::wstring, MaterialVariableMapping> MaterialVariablesMapping;

static std::string WStringToString(std::wstring wstr) {
	std::string str;
	std::transform(wstr.begin(), wstr.end(), std::back_inserter(str), [](wchar_t c) { return (char)c; });
	return str;
}

static std::wstring StringToWString(std::string str) {
	std::wstring wstr(str.begin(),str.end());
	return wstr;
}

static DirectX::XMFLOAT3 JsonToFloat3(nlohmann::json f3) {
	return DirectX::XMFLOAT3({ f3[0], f3[1], f3[2] });
}

static DirectX::XMFLOAT2 JsonToFloat2(nlohmann::json f2) {
	return DirectX::XMFLOAT2({ f2[0], f2[1] });
}

static nlohmann::json TransformMappingToJson(MaterialInitialValueMap mappedValues) {

	using namespace DirectX;
	nlohmann::json jMappedValues = nlohmann::json::array();

	std::transform(mappedValues.begin(), mappedValues.end(), std::back_inserter(jMappedValues), [](MaterialInitialValuePair pair) {
		nlohmann::json matInitialValue = nlohmann::json({});

		matInitialValue["variable"] = WStringToString(pair.first);
		matInitialValue["variableType"] = WStringToString(MaterialVariablesTypesStr[pair.second.variableType]);

		switch (pair.second.variableType) {
		case MAT_VAR_BOOLEAN:
		{
			auto value = std::any_cast<BOOLEAN>(pair.second.value);
			matInitialValue["value"] = value;
		}
		break;
		case MAT_VAR_INTEGER:
		{
			auto value = std::any_cast<INT>(pair.second.value);
			matInitialValue["value"] = value;
		}
		break;
		case MAT_VAR_UNSIGNED_INTEGER:
		{
			auto value = std::any_cast<UINT>(pair.second.value);
			matInitialValue["value"] = value;
		}
		break;
		case MAT_VAR_RGB:
			break;
		case MAT_VAR_RGBA:
			break;
		case MAT_VAR_FLOAT:
		{
			auto value = std::any_cast<FLOAT>(pair.second.value);
			matInitialValue["value"] = value;
		}
		break;
		case MAT_VAR_FLOAT2:
			break;
		case MAT_VAR_FLOAT3:
		{
			auto value = std::any_cast<XMFLOAT3>(pair.second.value);
			matInitialValue["value"] = { value.x , value.y, value.z };
		}
		break;
		case MAT_VAR_FLOAT4:
			break;
		case MAT_VAR_MATRIX4X4:
			break;
		}

		return matInitialValue;
	});

	return jMappedValues;

}

static MaterialInitialValueMap TransformJsonToMapping(nlohmann::json mappedValues) {
	
	using namespace DirectX;
	MaterialInitialValueMap map;

	std::transform(mappedValues.begin(), mappedValues.end(), std::inserter(map, map.end()), [](const nlohmann::json& value) {
		MaterialInitialValuePair pair;

		pair.first = StringToWString(value["variable"]);
		pair.second.variableType = StrToMaterialVariablesTypes[StringToWString(value["variableType"])];

		switch (pair.second.variableType) {
		case MAT_VAR_BOOLEAN:
		{
			bool valueB = value["value"];
			pair.second.value = valueB;
		}
		break;
		case MAT_VAR_INTEGER:
		{
			int valueI = value["value"];
			pair.second.value = valueI;
		}
		break;
		case MAT_VAR_UNSIGNED_INTEGER:
		{
			UINT valueUI = value["value"];
			pair.second.value = valueUI;
		}
		break;
		case MAT_VAR_RGB:
			break;
		case MAT_VAR_RGBA:
			break;
		case MAT_VAR_FLOAT:
		{
			float valueF = value["value"];
			pair.second.value = valueF;
		}
		break;
		case MAT_VAR_FLOAT2:
			break;
		case MAT_VAR_FLOAT3:
		{
			pair.second.value = XMFLOAT3({ value["value"][0] , value["value"][1], value["value"][2] });
		}
		break;
		case MAT_VAR_FLOAT4:
			break;
		case MAT_VAR_MATRIX4X4:
			break;
		}

		return pair;
	});

	return map;

}

static std::set<UINT> TransformJsonArrayToSet(nlohmann::json j) {
	std::set<UINT> set;
	for (auto& value : j) {
		UINT v = value;
		set.insert(v);
	}
	return set;
}

static std::map<DXGI_FORMAT, std::wstring> texturesFormatsToString = {
	{ DXGI_FORMAT_UNKNOWN, L"UNKNOWN" },
	{ DXGI_FORMAT_R32G32B32A32_TYPELESS, L"R32G32B32A32_TYPELESS" },
	{ DXGI_FORMAT_R32G32B32A32_FLOAT, L"R32G32B32A32_FLOAT" },
	{ DXGI_FORMAT_R32G32B32A32_UINT, L"R32G32B32A32_UINT" },
	{ DXGI_FORMAT_R32G32B32A32_SINT, L"R32G32B32A32_SINT" },
	{ DXGI_FORMAT_R32G32B32_TYPELESS, L"R32G32B32_TYPELESS" },
	{ DXGI_FORMAT_R32G32B32_FLOAT, L"R32G32B32_FLOAT" },
	{ DXGI_FORMAT_R32G32B32_UINT, L"R32G32B32_UINT" },
	{ DXGI_FORMAT_R32G32B32_SINT, L"R32G32B32_SINT" },
	{ DXGI_FORMAT_R16G16B16A16_TYPELESS, L"R16G16B16A16_TYPELESS" },
	{ DXGI_FORMAT_R16G16B16A16_FLOAT, L"R16G16B16A16_FLOAT" },
	{ DXGI_FORMAT_R16G16B16A16_UNORM, L"R16G16B16A16_UNORM" },
	{ DXGI_FORMAT_R16G16B16A16_UINT, L"R16G16B16A16_UINT" },
	{ DXGI_FORMAT_R16G16B16A16_SNORM, L"R16G16B16A16_SNORM" },
	{ DXGI_FORMAT_R16G16B16A16_SINT, L"R16G16B16A16_SINT" },
	{ DXGI_FORMAT_R32G32_TYPELESS, L"R32G32_TYPELESS" },
	{ DXGI_FORMAT_R32G32_FLOAT, L"R32G32_FLOAT" },
	{ DXGI_FORMAT_R32G32_UINT, L"R32G32_UINT" },
	{ DXGI_FORMAT_R32G32_SINT, L"R32G32_SINT" },
	{ DXGI_FORMAT_R32G8X24_TYPELESS, L"R32G8X24_TYPELESS" },
	{ DXGI_FORMAT_D32_FLOAT_S8X24_UINT, L"D32_FLOAT_S8X24_UINT" },
	{ DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS, L"R32_FLOAT_X8X24_TYPELESS" },
	{ DXGI_FORMAT_X32_TYPELESS_G8X24_UINT, L"X32_TYPELESS_G8X24_UINT" },
	{ DXGI_FORMAT_R10G10B10A2_TYPELESS, L"R10G10B10A2_TYPELESS" },
	{ DXGI_FORMAT_R10G10B10A2_UNORM, L"R10G10B10A2_UNORM" },
	{ DXGI_FORMAT_R10G10B10A2_UINT, L"R10G10B10A2_UINT" },
	{ DXGI_FORMAT_R11G11B10_FLOAT, L"R11G11B10_FLOAT" },
	{ DXGI_FORMAT_R8G8B8A8_TYPELESS, L"R8G8B8A8_TYPELESS" },
	{ DXGI_FORMAT_R8G8B8A8_UNORM, L"R8G8B8A8_UNORM" },
	{ DXGI_FORMAT_R8G8B8A8_UNORM_SRGB, L"R8G8B8A8_UNORM_SRGB" },
	{ DXGI_FORMAT_R8G8B8A8_UINT, L"R8G8B8A8_UINT" },
	{ DXGI_FORMAT_R8G8B8A8_SNORM, L"R8G8B8A8_SNORM" },
	{ DXGI_FORMAT_R8G8B8A8_SINT, L"R8G8B8A8_SINT" },
	{ DXGI_FORMAT_R16G16_TYPELESS, L"R16G16_TYPELESS" },
	{ DXGI_FORMAT_R16G16_FLOAT, L"R16G16_FLOAT" },
	{ DXGI_FORMAT_R16G16_UNORM, L"R16G16_UNORM" },
	{ DXGI_FORMAT_R16G16_UINT, L"R16G16_UINT" },
	{ DXGI_FORMAT_R16G16_SNORM, L"R16G16_SNORM" },
	{ DXGI_FORMAT_R16G16_SINT, L"R16G16_SINT" },
	{ DXGI_FORMAT_R32_TYPELESS, L"R32_TYPELESS" },
	{ DXGI_FORMAT_D32_FLOAT, L"D32_FLOAT" },
	{ DXGI_FORMAT_R32_FLOAT, L"R32_FLOAT" },
	{ DXGI_FORMAT_R32_UINT, L"R32_UINT" },
	{ DXGI_FORMAT_R32_SINT, L"R32_SINT" },
	{ DXGI_FORMAT_R24G8_TYPELESS, L"R24G8_TYPELESS" },
	{ DXGI_FORMAT_D24_UNORM_S8_UINT, L"D24_UNORM_S8_UINT" },
	{ DXGI_FORMAT_R24_UNORM_X8_TYPELESS, L"R24_UNORM_X8_TYPELESS" },
	{ DXGI_FORMAT_X24_TYPELESS_G8_UINT, L"X24_TYPELESS_G8_UINT" },
	{ DXGI_FORMAT_R8G8_TYPELESS, L"R8G8_TYPELESS" },
	{ DXGI_FORMAT_R8G8_UNORM, L"R8G8_UNORM" },
	{ DXGI_FORMAT_R8G8_UINT, L"R8G8_UINT" },
	{ DXGI_FORMAT_R8G8_SNORM, L"R8G8_SNORM" },
	{ DXGI_FORMAT_R8G8_SINT, L"R8G8_SINT" },
	{ DXGI_FORMAT_R16_TYPELESS, L"R16_TYPELESS" },
	{ DXGI_FORMAT_R16_FLOAT, L"R16_FLOAT" },
	{ DXGI_FORMAT_D16_UNORM, L"D16_UNORM" },
	{ DXGI_FORMAT_R16_UNORM, L"R16_UNORM" },
	{ DXGI_FORMAT_R16_UINT, L"R16_UINT" },
	{ DXGI_FORMAT_R16_SNORM, L"R16_SNORM" },
	{ DXGI_FORMAT_R16_SINT, L"R16_SINT" },
	{ DXGI_FORMAT_R8_TYPELESS, L"R8_TYPELESS" },
	{ DXGI_FORMAT_R8_UNORM, L"R8_UNORM" },
	{ DXGI_FORMAT_R8_UINT, L"R8_UINT" },
	{ DXGI_FORMAT_R8_SNORM, L"R8_SNORM" },
	{ DXGI_FORMAT_R8_SINT, L"R8_SINT" },
	{ DXGI_FORMAT_A8_UNORM, L"A8_UNORM" },
	{ DXGI_FORMAT_R1_UNORM, L"R1_UNORM" },
	{ DXGI_FORMAT_R9G9B9E5_SHAREDEXP, L"R9G9B9E5_SHAREDEXP" },
	{ DXGI_FORMAT_R8G8_B8G8_UNORM, L"R8G8_B8G8_UNORM" },
	{ DXGI_FORMAT_G8R8_G8B8_UNORM, L"G8R8_G8B8_UNORM" },
	{ DXGI_FORMAT_BC1_TYPELESS, L"BC1_TYPELESS" },
	{ DXGI_FORMAT_BC1_UNORM, L"BC1_UNORM" },
	{ DXGI_FORMAT_BC1_UNORM_SRGB, L"BC1_UNORM_SRGB" },
	{ DXGI_FORMAT_BC2_TYPELESS, L"BC2_TYPELESS" },
	{ DXGI_FORMAT_BC2_UNORM, L"BC2_UNORM" },
	{ DXGI_FORMAT_BC2_UNORM_SRGB, L"BC2_UNORM_SRGB" },
	{ DXGI_FORMAT_BC3_TYPELESS, L"BC3_TYPELESS" },
	{ DXGI_FORMAT_BC3_UNORM, L"BC3_UNORM" },
	{ DXGI_FORMAT_BC3_UNORM_SRGB, L"BC3_UNORM_SRGB" },
	{ DXGI_FORMAT_BC4_TYPELESS, L"BC4_TYPELESS" },
	{ DXGI_FORMAT_BC4_UNORM, L"BC4_UNORM" },
	{ DXGI_FORMAT_BC4_SNORM, L"BC4_SNORM" },
	{ DXGI_FORMAT_BC5_TYPELESS, L"BC5_TYPELESS" },
	{ DXGI_FORMAT_BC5_UNORM, L"BC5_UNORM" },
	{ DXGI_FORMAT_BC5_SNORM, L"BC5_SNORM" },
	{ DXGI_FORMAT_B5G6R5_UNORM, L"B5G6R5_UNORM" },
	{ DXGI_FORMAT_B5G5R5A1_UNORM, L"B5G5R5A1_UNORM" },
	{ DXGI_FORMAT_B8G8R8A8_UNORM, L"B8G8R8A8_UNORM" },
	{ DXGI_FORMAT_B8G8R8X8_UNORM, L"B8G8R8X8_UNORM" },
	{ DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM, L"R10G10B10_XR_BIAS_A2_UNORM" },
	{ DXGI_FORMAT_B8G8R8A8_TYPELESS, L"B8G8R8A8_TYPELESS" },
	{ DXGI_FORMAT_B8G8R8A8_UNORM_SRGB, L"B8G8R8A8_UNORM_SRGB" },
	{ DXGI_FORMAT_B8G8R8X8_TYPELESS, L"B8G8R8X8_TYPELESS" },
	{ DXGI_FORMAT_B8G8R8X8_UNORM_SRGB, L"B8G8R8X8_UNORM_SRGB" },
	{ DXGI_FORMAT_BC6H_TYPELESS, L"BC6H_TYPELESS" },
	{ DXGI_FORMAT_BC6H_UF16, L"BC6H_UF16" },
	{ DXGI_FORMAT_BC6H_SF16, L"BC6H_SF16" },
	{ DXGI_FORMAT_BC7_TYPELESS, L"BC7_TYPELESS" },
	{ DXGI_FORMAT_BC7_UNORM, L"BC7_UNORM" },
	{ DXGI_FORMAT_BC7_UNORM_SRGB, L"BC7_UNORM_SRGB" },
	{ DXGI_FORMAT_AYUV, L"AYUV" },
	{ DXGI_FORMAT_Y410, L"Y410" },
	{ DXGI_FORMAT_Y416, L"Y416" },
	{ DXGI_FORMAT_NV12, L"NV12" },
	{ DXGI_FORMAT_P010, L"P010" },
	{ DXGI_FORMAT_P016, L"P016" },
	{ DXGI_FORMAT_420_OPAQUE, L"420_OPAQUE" },
	{ DXGI_FORMAT_YUY2, L"YUY2" },
	{ DXGI_FORMAT_Y210, L"Y210" },
	{ DXGI_FORMAT_Y216, L"Y216" },
	{ DXGI_FORMAT_NV11, L"NV11" },
	{ DXGI_FORMAT_AI44, L"AI44" },
	{ DXGI_FORMAT_IA44, L"IA44" },
	{ DXGI_FORMAT_P8, L"P8" },
	{ DXGI_FORMAT_A8P8, L"A8P8" },
	{ DXGI_FORMAT_B4G4R4A4_UNORM, L"B4G4R4A4_UNORM" },
	{ DXGI_FORMAT_P208, L"P208" },
	{ DXGI_FORMAT_V208, L"V208" },
	{ DXGI_FORMAT_V408, L"V408" },
	{ DXGI_FORMAT_SAMPLER_FEEDBACK_MIN_MIP_OPAQUE,  L"SAMPLER_FEEDBACK_MIN_MIP_OPAQUE" },
	{ DXGI_FORMAT_SAMPLER_FEEDBACK_MIP_REGION_USED_OPAQUE, L"SAMPLER_FEEDBACK_MIP_REGION_USED_OPAQUE" },
	{ DXGI_FORMAT_A4B4G4R4_UNORM, L"A4B4G4R4_UNORM" },
	{ DXGI_FORMAT_FORCE_UINT, L"FORCE_UINT" }
};

static std::map<std::wstring, DXGI_FORMAT> stringToTextureFormat = {
	{ L"UNKNOWN", DXGI_FORMAT_UNKNOWN },
	{ L"R32G32B32A32_TYPELESS", DXGI_FORMAT_R32G32B32A32_TYPELESS },
	{ L"R32G32B32A32_FLOAT", DXGI_FORMAT_R32G32B32A32_FLOAT },
	{ L"R32G32B32A32_UINT", DXGI_FORMAT_R32G32B32A32_UINT },
	{ L"R32G32B32A32_SINT", DXGI_FORMAT_R32G32B32A32_SINT },
	{ L"R32G32B32_TYPELESS", DXGI_FORMAT_R32G32B32_TYPELESS },
	{ L"R32G32B32_FLOAT", DXGI_FORMAT_R32G32B32_FLOAT },
	{ L"R32G32B32_UINT", DXGI_FORMAT_R32G32B32_UINT },
	{ L"R32G32B32_SINT", DXGI_FORMAT_R32G32B32_SINT },
	{ L"R16G16B16A16_TYPELESS", DXGI_FORMAT_R16G16B16A16_TYPELESS },
	{ L"R16G16B16A16_FLOAT", DXGI_FORMAT_R16G16B16A16_FLOAT },
	{ L"R16G16B16A16_UNORM", DXGI_FORMAT_R16G16B16A16_UNORM },
	{ L"R16G16B16A16_UINT", DXGI_FORMAT_R16G16B16A16_UINT },
	{ L"R16G16B16A16_SNORM", DXGI_FORMAT_R16G16B16A16_SNORM },
	{ L"R16G16B16A16_SINT", DXGI_FORMAT_R16G16B16A16_SINT },
	{ L"R32G32_TYPELESS", DXGI_FORMAT_R32G32_TYPELESS },
	{ L"R32G32_FLOAT", DXGI_FORMAT_R32G32_FLOAT },
	{ L"R32G32_UINT", DXGI_FORMAT_R32G32_UINT },
	{ L"R32G32_SINT", DXGI_FORMAT_R32G32_SINT },
	{ L"R32G8X24_TYPELESS", DXGI_FORMAT_R32G8X24_TYPELESS },
	{ L"D32_FLOAT_S8X24_UINT", DXGI_FORMAT_D32_FLOAT_S8X24_UINT },
	{ L"R32_FLOAT_X8X24_TYPELESS", DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS },
	{ L"X32_TYPELESS_G8X24_UINT", DXGI_FORMAT_X32_TYPELESS_G8X24_UINT },
	{ L"R10G10B10A2_TYPELESS", DXGI_FORMAT_R10G10B10A2_TYPELESS },
	{ L"R10G10B10A2_UNORM", DXGI_FORMAT_R10G10B10A2_UNORM },
	{ L"R10G10B10A2_UINT", DXGI_FORMAT_R10G10B10A2_UINT },
	{ L"R11G11B10_FLOAT", DXGI_FORMAT_R11G11B10_FLOAT },
	{ L"R8G8B8A8_TYPELESS", DXGI_FORMAT_R8G8B8A8_TYPELESS },
	{ L"R8G8B8A8_UNORM", DXGI_FORMAT_R8G8B8A8_UNORM },
	{ L"R8G8B8A8_UNORM_SRGB", DXGI_FORMAT_R8G8B8A8_UNORM_SRGB },
	{ L"R8G8B8A8_UINT", DXGI_FORMAT_R8G8B8A8_UINT },
	{ L"R8G8B8A8_SNORM", DXGI_FORMAT_R8G8B8A8_SNORM },
	{ L"R8G8B8A8_SINT", DXGI_FORMAT_R8G8B8A8_SINT },
	{ L"R16G16_TYPELESS", DXGI_FORMAT_R16G16_TYPELESS },
	{ L"R16G16_FLOAT", DXGI_FORMAT_R16G16_FLOAT },
	{ L"R16G16_UNORM", DXGI_FORMAT_R16G16_UNORM },
	{ L"R16G16_UINT", DXGI_FORMAT_R16G16_UINT },
	{ L"R16G16_SNORM", DXGI_FORMAT_R16G16_SNORM },
	{ L"R16G16_SINT", DXGI_FORMAT_R16G16_SINT },
	{ L"R32_TYPELESS", DXGI_FORMAT_R32_TYPELESS },
	{ L"D32_FLOAT", DXGI_FORMAT_D32_FLOAT },
	{ L"R32_FLOAT", DXGI_FORMAT_R32_FLOAT },
	{ L"R32_UINT", DXGI_FORMAT_R32_UINT },
	{ L"R32_SINT", DXGI_FORMAT_R32_SINT },
	{ L"R24G8_TYPELESS", DXGI_FORMAT_R24G8_TYPELESS },
	{ L"D24_UNORM_S8_UINT", DXGI_FORMAT_D24_UNORM_S8_UINT },
	{ L"R24_UNORM_X8_TYPELESS", DXGI_FORMAT_R24_UNORM_X8_TYPELESS },
	{ L"X24_TYPELESS_G8_UINT", DXGI_FORMAT_X24_TYPELESS_G8_UINT },
	{ L"R8G8_TYPELESS", DXGI_FORMAT_R8G8_TYPELESS },
	{ L"R8G8_UNORM", DXGI_FORMAT_R8G8_UNORM },
	{ L"R8G8_UINT", DXGI_FORMAT_R8G8_UINT },
	{ L"R8G8_SNORM", DXGI_FORMAT_R8G8_SNORM },
	{ L"R8G8_SINT", DXGI_FORMAT_R8G8_SINT },
	{ L"R16_TYPELESS", DXGI_FORMAT_R16_TYPELESS },
	{ L"R16_FLOAT", DXGI_FORMAT_R16_FLOAT },
	{ L"D16_UNORM", DXGI_FORMAT_D16_UNORM },
	{ L"R16_UNORM", DXGI_FORMAT_R16_UNORM },
	{ L"R16_UINT", DXGI_FORMAT_R16_UINT },
	{ L"R16_SNORM", DXGI_FORMAT_R16_SNORM },
	{ L"R16_SINT", DXGI_FORMAT_R16_SINT },
	{ L"R8_TYPELESS", DXGI_FORMAT_R8_TYPELESS },
	{ L"R8_UNORM", DXGI_FORMAT_R8_UNORM },
	{ L"R8_UINT", DXGI_FORMAT_R8_UINT },
	{ L"R8_SNORM", DXGI_FORMAT_R8_SNORM },
	{ L"R8_SINT", DXGI_FORMAT_R8_SINT },
	{ L"A8_UNORM", DXGI_FORMAT_A8_UNORM },
	{ L"R1_UNORM", DXGI_FORMAT_R1_UNORM },
	{ L"R9G9B9E5_SHAREDEXP", DXGI_FORMAT_R9G9B9E5_SHAREDEXP },
	{ L"R8G8_B8G8_UNORM", DXGI_FORMAT_R8G8_B8G8_UNORM },
	{ L"G8R8_G8B8_UNORM", DXGI_FORMAT_G8R8_G8B8_UNORM },
	{ L"BC1_TYPELESS", DXGI_FORMAT_BC1_TYPELESS },
	{ L"BC1_UNORM", DXGI_FORMAT_BC1_UNORM },
	{ L"BC1_UNORM_SRGB", DXGI_FORMAT_BC1_UNORM_SRGB },
	{ L"BC2_TYPELESS", DXGI_FORMAT_BC2_TYPELESS },
	{ L"BC2_UNORM", DXGI_FORMAT_BC2_UNORM },
	{ L"BC2_UNORM_SRGB", DXGI_FORMAT_BC2_UNORM_SRGB },
	{ L"BC3_TYPELESS", DXGI_FORMAT_BC3_TYPELESS },
	{ L"BC3_UNORM", DXGI_FORMAT_BC3_UNORM },
	{ L"BC3_UNORM_SRGB", DXGI_FORMAT_BC3_UNORM_SRGB },
	{ L"BC4_TYPELESS", DXGI_FORMAT_BC4_TYPELESS },
	{ L"BC4_UNORM", DXGI_FORMAT_BC4_UNORM },
	{ L"BC4_SNORM", DXGI_FORMAT_BC4_SNORM },
	{ L"BC5_TYPELESS", DXGI_FORMAT_BC5_TYPELESS },
	{ L"BC5_UNORM", DXGI_FORMAT_BC5_UNORM },
	{ L"BC5_SNORM", DXGI_FORMAT_BC5_SNORM },
	{ L"B5G6R5_UNORM", DXGI_FORMAT_B5G6R5_UNORM },
	{ L"B5G5R5A1_UNORM", DXGI_FORMAT_B5G5R5A1_UNORM },
	{ L"B8G8R8A8_UNORM", DXGI_FORMAT_B8G8R8A8_UNORM },
	{ L"B8G8R8X8_UNORM", DXGI_FORMAT_B8G8R8X8_UNORM },
	{ L"R10G10B10_XR_BIAS_A2_UNORM", DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM },
	{ L"B8G8R8A8_TYPELESS", DXGI_FORMAT_B8G8R8A8_TYPELESS },
	{ L"B8G8R8A8_UNORM_SRGB", DXGI_FORMAT_B8G8R8A8_UNORM_SRGB },
	{ L"B8G8R8X8_TYPELESS", DXGI_FORMAT_B8G8R8X8_TYPELESS },
	{ L"B8G8R8X8_UNORM_SRGB", DXGI_FORMAT_B8G8R8X8_UNORM_SRGB },
	{ L"BC6H_TYPELESS", DXGI_FORMAT_BC6H_TYPELESS },
	{ L"BC6H_UF16", DXGI_FORMAT_BC6H_UF16 },
	{ L"BC6H_SF16", DXGI_FORMAT_BC6H_SF16 },
	{ L"BC7_TYPELESS", DXGI_FORMAT_BC7_TYPELESS },
	{ L"BC7_UNORM", DXGI_FORMAT_BC7_UNORM },
	{ L"BC7_UNORM_SRGB", DXGI_FORMAT_BC7_UNORM_SRGB },
	{ L"AYUV", DXGI_FORMAT_AYUV },
	{ L"Y410", DXGI_FORMAT_Y410 },
	{ L"Y416", DXGI_FORMAT_Y416 },
	{ L"NV12", DXGI_FORMAT_NV12 },
	{ L"P010", DXGI_FORMAT_P010 },
	{ L"P016", DXGI_FORMAT_P016 },
	{ L"420_OPAQUE", DXGI_FORMAT_420_OPAQUE },
	{ L"YUY2", DXGI_FORMAT_YUY2 },
	{ L"Y210", DXGI_FORMAT_Y210 },
	{ L"Y216", DXGI_FORMAT_Y216 },
	{ L"NV11", DXGI_FORMAT_NV11 },
	{ L"AI44", DXGI_FORMAT_AI44 },
	{ L"IA44", DXGI_FORMAT_IA44 },
	{ L"P8", DXGI_FORMAT_P8 },
	{ L"A8P8", DXGI_FORMAT_A8P8 },
	{ L"B4G4R4A4_UNORM", DXGI_FORMAT_B4G4R4A4_UNORM },
	{ L"P208", DXGI_FORMAT_P208 },
	{ L"V208", DXGI_FORMAT_V208 },
	{ L"V408", DXGI_FORMAT_V408 },
	{ L"SAMPLER_FEEDBACK_MIN_MIP_OPAQUE", DXGI_FORMAT_SAMPLER_FEEDBACK_MIN_MIP_OPAQUE },
	{ L"SAMPLER_FEEDBACK_MIP_REGION_USED_OPAQUE", DXGI_FORMAT_SAMPLER_FEEDBACK_MIP_REGION_USED_OPAQUE },
	{ L"A4B4G4R4_UNORM", DXGI_FORMAT_A4B4G4R4_UNORM },
	{ L"FORCE_UINT", DXGI_FORMAT_FORCE_UINT }
};

static std::map<D3D12_FILTER, std::wstring> filterToString = {
	{ D3D12_FILTER_MIN_MAG_MIP_POINT, L"MIN_MAG_MIP_POINT" },
	{ D3D12_FILTER_MIN_MAG_POINT_MIP_LINEAR, L"MIN_MAG_POINT_MIP_LINEAR" },
	{ D3D12_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT, L"MIN_POINT_MAG_LINEAR_MIP_POINT" },
	{ D3D12_FILTER_MIN_POINT_MAG_MIP_LINEAR, L"MIN_POINT_MAG_MIP_LINEAR" },
	{ D3D12_FILTER_MIN_LINEAR_MAG_MIP_POINT, L"MIN_LINEAR_MAG_MIP_POINT" },
	{ D3D12_FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR, L"MIN_LINEAR_MAG_POINT_MIP_LINEAR" },
	{ D3D12_FILTER_MIN_MAG_LINEAR_MIP_POINT, L"MIN_MAG_LINEAR_MIP_POINT" },
	{ D3D12_FILTER_MIN_MAG_MIP_LINEAR, L"MIN_MAG_MIP_LINEAR" },
	{ D3D12_FILTER_MIN_MAG_ANISOTROPIC_MIP_POINT, L"MIN_MAG_ANISOTROPIC_MIP_POINT" },
	{ D3D12_FILTER_ANISOTROPIC, L"ANISOTROPIC" },
	{ D3D12_FILTER_COMPARISON_MIN_MAG_MIP_POINT, L"COMPARISON_MIN_MAG_MIP_POINT" },
	{ D3D12_FILTER_COMPARISON_MIN_MAG_POINT_MIP_LINEAR, L"COMPARISON_MIN_MAG_POINT_MIP_LINEAR" },
	{ D3D12_FILTER_COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT, L"COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT" },
	{ D3D12_FILTER_COMPARISON_MIN_POINT_MAG_MIP_LINEAR, L"COMPARISON_MIN_POINT_MAG_MIP_LINEAR" },
	{ D3D12_FILTER_COMPARISON_MIN_LINEAR_MAG_MIP_POINT, L"COMPARISON_MIN_LINEAR_MAG_MIP_POINT" },
	{ D3D12_FILTER_COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR, L"COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR" },
	{ D3D12_FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT, L"COMPARISON_MIN_MAG_LINEAR_MIP_POINT" },
	{ D3D12_FILTER_COMPARISON_MIN_MAG_MIP_LINEAR, L"COMPARISON_MIN_MAG_MIP_LINEAR" },
	{ D3D12_FILTER_COMPARISON_MIN_MAG_ANISOTROPIC_MIP_POINT, L"COMPARISON_MIN_MAG_ANISOTROPIC_MIP_POINT" },
	{ D3D12_FILTER_COMPARISON_ANISOTROPIC, L"COMPARISON_ANISOTROPIC" },
	{ D3D12_FILTER_MINIMUM_MIN_MAG_MIP_POINT, L"MINIMUM_MIN_MAG_MIP_POINT" },
	{ D3D12_FILTER_MINIMUM_MIN_MAG_POINT_MIP_LINEAR, L"MINIMUM_MIN_MAG_POINT_MIP_LINEAR" },
	{ D3D12_FILTER_MINIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT, L"MINIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT" },
	{ D3D12_FILTER_MINIMUM_MIN_POINT_MAG_MIP_LINEAR, L"MINIMUM_MIN_POINT_MAG_MIP_LINEAR" },
	{ D3D12_FILTER_MINIMUM_MIN_LINEAR_MAG_MIP_POINT, L"MINIMUM_MIN_LINEAR_MAG_MIP_POINT" },
	{ D3D12_FILTER_MINIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR, L"MINIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR" },
	{ D3D12_FILTER_MINIMUM_MIN_MAG_LINEAR_MIP_POINT, L"MINIMUM_MIN_MAG_LINEAR_MIP_POINT" },
	{ D3D12_FILTER_MINIMUM_MIN_MAG_MIP_LINEAR, L"MINIMUM_MIN_MAG_MIP_LINEAR" },
	{ D3D12_FILTER_MINIMUM_MIN_MAG_ANISOTROPIC_MIP_POINT, L"MINIMUM_MIN_MAG_ANISOTROPIC_MIP_POINT" },
	{ D3D12_FILTER_MINIMUM_ANISOTROPIC, L"MINIMUM_ANISOTROPIC" },
	{ D3D12_FILTER_MAXIMUM_MIN_MAG_MIP_POINT, L"MAXIMUM_MIN_MAG_MIP_POINT" },
	{ D3D12_FILTER_MAXIMUM_MIN_MAG_POINT_MIP_LINEAR, L"MAXIMUM_MIN_MAG_POINT_MIP_LINEAR" },
	{ D3D12_FILTER_MAXIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT, L"MAXIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT" },
	{ D3D12_FILTER_MAXIMUM_MIN_POINT_MAG_MIP_LINEAR, L"MAXIMUM_MIN_POINT_MAG_MIP_LINEAR" },
	{ D3D12_FILTER_MAXIMUM_MIN_LINEAR_MAG_MIP_POINT, L"MAXIMUM_MIN_LINEAR_MAG_MIP_POINT" },
	{ D3D12_FILTER_MAXIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR, L"MAXIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR" },
	{ D3D12_FILTER_MAXIMUM_MIN_MAG_LINEAR_MIP_POINT, L"MAXIMUM_MIN_MAG_LINEAR_MIP_POINT" },
	{ D3D12_FILTER_MAXIMUM_MIN_MAG_MIP_LINEAR, L"MAXIMUM_MIN_MAG_MIP_LINEAR" },
	{ D3D12_FILTER_MAXIMUM_MIN_MAG_ANISOTROPIC_MIP_POINT, L"MAXIMUM_MIN_MAG_ANISOTROPIC_MIP_POINT" },
	{ D3D12_FILTER_MAXIMUM_ANISOTROPIC, L"MAXIMUM_ANISOTROPIC" }
};

static std::map<std::wstring, D3D12_FILTER> stringToFilter = {
	{ L"MIN_MAG_MIP_POINT", D3D12_FILTER_MIN_MAG_MIP_POINT },
	{ L"MIN_MAG_POINT_MIP_LINEAR", D3D12_FILTER_MIN_MAG_POINT_MIP_LINEAR },
	{ L"MIN_POINT_MAG_LINEAR_MIP_POINT", D3D12_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT },
	{ L"MIN_POINT_MAG_MIP_LINEAR", D3D12_FILTER_MIN_POINT_MAG_MIP_LINEAR },
	{ L"MIN_LINEAR_MAG_MIP_POINT", D3D12_FILTER_MIN_LINEAR_MAG_MIP_POINT },
	{ L"MIN_LINEAR_MAG_POINT_MIP_LINEAR", D3D12_FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR },
	{ L"MIN_MAG_LINEAR_MIP_POINT", D3D12_FILTER_MIN_MAG_LINEAR_MIP_POINT },
	{ L"MIN_MAG_MIP_LINEAR", D3D12_FILTER_MIN_MAG_MIP_LINEAR },
	{ L"MIN_MAG_ANISOTROPIC_MIP_POINT", D3D12_FILTER_MIN_MAG_ANISOTROPIC_MIP_POINT },
	{ L"ANISOTROPIC", D3D12_FILTER_ANISOTROPIC },
	{ L"COMPARISON_MIN_MAG_MIP_POINT", D3D12_FILTER_COMPARISON_MIN_MAG_MIP_POINT },
	{ L"COMPARISON_MIN_MAG_POINT_MIP_LINEAR", D3D12_FILTER_COMPARISON_MIN_MAG_POINT_MIP_LINEAR },
	{ L"COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT", D3D12_FILTER_COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT },
	{ L"COMPARISON_MIN_POINT_MAG_MIP_LINEAR", D3D12_FILTER_COMPARISON_MIN_POINT_MAG_MIP_LINEAR },
	{ L"COMPARISON_MIN_LINEAR_MAG_MIP_POINT", D3D12_FILTER_COMPARISON_MIN_LINEAR_MAG_MIP_POINT },
	{ L"COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR", D3D12_FILTER_COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR },
	{ L"COMPARISON_MIN_MAG_LINEAR_MIP_POINT", D3D12_FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT },
	{ L"COMPARISON_MIN_MAG_MIP_LINEAR", D3D12_FILTER_COMPARISON_MIN_MAG_MIP_LINEAR },
	{ L"COMPARISON_MIN_MAG_ANISOTROPIC_MIP_POINT", D3D12_FILTER_COMPARISON_MIN_MAG_ANISOTROPIC_MIP_POINT },
	{ L"COMPARISON_ANISOTROPIC", D3D12_FILTER_COMPARISON_ANISOTROPIC },
	{ L"MINIMUM_MIN_MAG_MIP_POINT", D3D12_FILTER_MINIMUM_MIN_MAG_MIP_POINT },
	{ L"MINIMUM_MIN_MAG_POINT_MIP_LINEAR", D3D12_FILTER_MINIMUM_MIN_MAG_POINT_MIP_LINEAR },
	{ L"MINIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT", D3D12_FILTER_MINIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT },
	{ L"MINIMUM_MIN_POINT_MAG_MIP_LINEAR", D3D12_FILTER_MINIMUM_MIN_POINT_MAG_MIP_LINEAR },
	{ L"MINIMUM_MIN_LINEAR_MAG_MIP_POINT", D3D12_FILTER_MINIMUM_MIN_LINEAR_MAG_MIP_POINT },
	{ L"MINIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR", D3D12_FILTER_MINIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR },
	{ L"MINIMUM_MIN_MAG_LINEAR_MIP_POINT", D3D12_FILTER_MINIMUM_MIN_MAG_LINEAR_MIP_POINT },
	{ L"MINIMUM_MIN_MAG_MIP_LINEAR", D3D12_FILTER_MINIMUM_MIN_MAG_MIP_LINEAR },
	{ L"MINIMUM_MIN_MAG_ANISOTROPIC_MIP_POINT", D3D12_FILTER_MINIMUM_MIN_MAG_ANISOTROPIC_MIP_POINT },
	{ L"MINIMUM_ANISOTROPIC", D3D12_FILTER_MINIMUM_ANISOTROPIC },
	{ L"MAXIMUM_MIN_MAG_MIP_POINT", D3D12_FILTER_MAXIMUM_MIN_MAG_MIP_POINT },
	{ L"MAXIMUM_MIN_MAG_POINT_MIP_LINEAR", D3D12_FILTER_MAXIMUM_MIN_MAG_POINT_MIP_LINEAR },
	{ L"MAXIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT", D3D12_FILTER_MAXIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT },
	{ L"MAXIMUM_MIN_POINT_MAG_MIP_LINEAR", D3D12_FILTER_MAXIMUM_MIN_POINT_MAG_MIP_LINEAR },
	{ L"MAXIMUM_MIN_LINEAR_MAG_MIP_POINT", D3D12_FILTER_MAXIMUM_MIN_LINEAR_MAG_MIP_POINT },
	{ L"MAXIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR", D3D12_FILTER_MAXIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR },
	{ L"MAXIMUM_MIN_MAG_LINEAR_MIP_POINT", D3D12_FILTER_MAXIMUM_MIN_MAG_LINEAR_MIP_POINT },
	{ L"MAXIMUM_MIN_MAG_MIP_LINEAR", D3D12_FILTER_MAXIMUM_MIN_MAG_MIP_LINEAR },
	{ L"MAXIMUM_MIN_MAG_ANISOTROPIC_MIP_POINT", D3D12_FILTER_MAXIMUM_MIN_MAG_ANISOTROPIC_MIP_POINT },
	{ L"MAXIMUM_ANISOTROPIC", D3D12_FILTER_MAXIMUM_ANISOTROPIC }
};

static std::map<D3D12_TEXTURE_ADDRESS_MODE, std::wstring> textureAddressModeToString = {
	{ D3D12_TEXTURE_ADDRESS_MODE_WRAP, L"ADDRESS_MODE_WRAP" },
	{ D3D12_TEXTURE_ADDRESS_MODE_MIRROR, L"ADDRESS_MODE_MIRROR" },
	{ D3D12_TEXTURE_ADDRESS_MODE_CLAMP, L"ADDRESS_MODE_CLAMP" },
	{ D3D12_TEXTURE_ADDRESS_MODE_BORDER, L"ADDRESS_MODE_BORDER" },
	{ D3D12_TEXTURE_ADDRESS_MODE_MIRROR_ONCE, L"ADDRESS_MODE_MIRROR_ONCE" }
};

static std::map<std::wstring, D3D12_TEXTURE_ADDRESS_MODE> stringToTextureAddressMode = {
	{ L"ADDRESS_MODE_WRAP", D3D12_TEXTURE_ADDRESS_MODE_WRAP },
	{ L"ADDRESS_MODE_MIRROR", D3D12_TEXTURE_ADDRESS_MODE_MIRROR },
	{ L"ADDRESS_MODE_CLAMP", D3D12_TEXTURE_ADDRESS_MODE_CLAMP },
	{ L"ADDRESS_MODE_BORDER", D3D12_TEXTURE_ADDRESS_MODE_BORDER },
	{ L"ADDRESS_MODE_MIRROR_ONCE", D3D12_TEXTURE_ADDRESS_MODE_MIRROR_ONCE }
};

static std::map<D3D12_COMPARISON_FUNC, std::wstring> comparisonFuncToString = {
	{ D3D12_COMPARISON_FUNC_NONE, L"NONE" },
	{ D3D12_COMPARISON_FUNC_NEVER, L"NEVER" },
	{ D3D12_COMPARISON_FUNC_LESS, L"LESS" },
	{ D3D12_COMPARISON_FUNC_EQUAL, L"EQUAL" },
	{ D3D12_COMPARISON_FUNC_LESS_EQUAL, L"LESS_EQUAL" },
	{ D3D12_COMPARISON_FUNC_GREATER, L"GREATER" },
	{ D3D12_COMPARISON_FUNC_NOT_EQUAL, L"NOT_EQUAL" },
	{ D3D12_COMPARISON_FUNC_GREATER_EQUAL, L"GREATER_EQUAL" },
	{ D3D12_COMPARISON_FUNC_ALWAYS, L"ALWAYS" }
};

static std::map<std::wstring, D3D12_COMPARISON_FUNC> stringToComparisonFunc = {
	{ L"NONE", D3D12_COMPARISON_FUNC_NONE },
	{ L"NEVER", D3D12_COMPARISON_FUNC_NEVER },
	{ L"LESS", D3D12_COMPARISON_FUNC_LESS },
	{ L"EQUAL", D3D12_COMPARISON_FUNC_EQUAL },
	{ L"LESS_EQUAL", D3D12_COMPARISON_FUNC_LESS_EQUAL },
	{ L"GREATER", D3D12_COMPARISON_FUNC_GREATER },
	{ L"NOT_EQUAL", D3D12_COMPARISON_FUNC_NOT_EQUAL },
	{ L"GREATER_EQUAL", D3D12_COMPARISON_FUNC_GREATER_EQUAL },
	{ L"ALWAYS", D3D12_COMPARISON_FUNC_ALWAYS }
};

static std::map<D3D12_STATIC_BORDER_COLOR, std::wstring> borderColorToString = {
	{ D3D12_STATIC_BORDER_COLOR_TRANSPARENT_BLACK, L"TRANSPARENT_BLACK" },
	{ D3D12_STATIC_BORDER_COLOR_OPAQUE_BLACK, L"OPAQUE_BLACK" },
	{ D3D12_STATIC_BORDER_COLOR_OPAQUE_WHITE, L"OPAQUE_WHITE" },
	{ D3D12_STATIC_BORDER_COLOR_OPAQUE_BLACK_UINT, L"OPAQUE_BLACK_UINT" },
	{ D3D12_STATIC_BORDER_COLOR_OPAQUE_WHITE_UINT, L"OPAQUE_WHITE_UINT" }
};

static std::map<std::wstring, D3D12_STATIC_BORDER_COLOR> stringToBorderColor = {
	{ L"TRANSPARENT_BLACK", D3D12_STATIC_BORDER_COLOR_TRANSPARENT_BLACK },
	{ L"OPAQUE_BLACK", D3D12_STATIC_BORDER_COLOR_OPAQUE_BLACK },
	{ L"OPAQUE_WHITE", D3D12_STATIC_BORDER_COLOR_OPAQUE_WHITE },
	{ L"OPAQUE_BLACK_UINT", D3D12_STATIC_BORDER_COLOR_OPAQUE_BLACK_UINT },
	{ L"OPAQUE_WHITE_UINT", D3D12_STATIC_BORDER_COLOR_OPAQUE_WHITE_UINT }
};

static std::map<D3D12_SHADER_VISIBILITY, std::wstring> shaderVisibilityToString = {
	{ D3D12_SHADER_VISIBILITY_ALL, L"ALL" },
	{ D3D12_SHADER_VISIBILITY_VERTEX, L"VERTEX" },
	{ D3D12_SHADER_VISIBILITY_HULL, L"HULL" },
	{ D3D12_SHADER_VISIBILITY_DOMAIN, L"DOMAIN" },
	{ D3D12_SHADER_VISIBILITY_GEOMETRY, L"GEOMETRY" },
	{ D3D12_SHADER_VISIBILITY_PIXEL, L"PIXEL" },
	{ D3D12_SHADER_VISIBILITY_AMPLIFICATION, L"AMPLIFICATION" },
	{ D3D12_SHADER_VISIBILITY_MESH, L"MESH" }
};

static std::map<std::wstring, D3D12_SHADER_VISIBILITY> stringToShaderVisibility = {
	{ L"ALL", D3D12_SHADER_VISIBILITY_ALL},
	{ L"VERTEX", D3D12_SHADER_VISIBILITY_VERTEX },
	{ L"HULL", D3D12_SHADER_VISIBILITY_HULL },
	{ L"DOMAIN", D3D12_SHADER_VISIBILITY_DOMAIN },
	{ L"GEOMETRY", D3D12_SHADER_VISIBILITY_GEOMETRY },
	{ L"PIXEL", D3D12_SHADER_VISIBILITY_PIXEL },
	{ L"AMPLIFICATION", D3D12_SHADER_VISIBILITY_AMPLIFICATION },
	{ L"MESH", D3D12_SHADER_VISIBILITY_MESH }
};

static std::map<SOUND_EFFECT_INSTANCE_FLAGS, std::wstring> soundEffectInstanceFlagToString = {
	{ SoundEffectInstance_Default, L"Default" },
	{ SoundEffectInstance_Use3D, L"Use3D" },
	{ SoundEffectInstance_ReverbUseFilters,	L"ReverbUseFilters" },
	{ SoundEffectInstance_NoSetPitch,	L"NoSetPitch" },
	{ SoundEffectInstance_UseRedirectLFE,	L"UseRedirectLFE" }
};

static std::map<std::wstring, SOUND_EFFECT_INSTANCE_FLAGS> stringToSoundEffectInstanceFlag = {
	{ L"Default", SoundEffectInstance_Default },
	{ L"Use3D",	SoundEffectInstance_Use3D },
	{ L"ReverbUseFilters", SoundEffectInstance_ReverbUseFilters },
	{ L"NoSetPitch", SoundEffectInstance_NoSetPitch },
	{ L"UseRedirectLFE", SoundEffectInstance_UseRedirectLFE },
};

static const std::wstring defaultLevelsFolder = L"Levels/";
static const std::wstring defaultTemplatesFolder = L"Templates/";
static const std::wstring defaultLevelName = L"baseLevel.json";

template<typename T>
void replaceFromJson(T& value, nlohmann::json& object, const std::string& key) {
	if(object.contains(key)) value = static_cast<T>(object[key]);
}

template<typename T, typename E>
bool bytesHas(T bytes, E flag ) {
	return (bytes & flag) == flag;
}
